In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
# https://docs.google.com/spreadsheets/d/1wypsJCSWRFAedEHbkzHUUa49OimYSngPIs4uN-xsV4U/edit?usp=sharing
id="1wypsJCSWRFAedEHbkzHUUa49OimYSngPIs4uN-xsV4U"
xls=pd.ExcelFile(f" https://docs.google.com/spreadsheets/d/{id}/export?format=xlsx")
df=pd.read_excel(xls)
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8   76000

In [3]:
df.bedroom.median()

3.5

In [4]:
import math
df_bedroom=math.floor(df.bedroom.median())
df_bedroom

3

In [5]:
df.bedroom=df.bedroom.fillna(df_bedroom)

In [8]:
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8   76000

In [7]:
# there two type of variable i.e dependent variable and independent variable (when those is target to find the value this
# is the dependent variable other than is the independent variable)

In [10]:
lr=linear_model.LinearRegression()
lr.fit(df[['area','bedroom','age']],df.price)

LinearRegression()

In [14]:
lr.coef_

array([   -153.45, -106395.  ,    8565.  ])

In [15]:
lr.intercept_

1209654.999999999

In [16]:
lr.predict([[3000,3,40]])

D:\Users\Lenovo\AppData\Local\anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([772720.])

In [17]:
lr.predict([[2500,4,5]])

D:\Users\Lenovo\AppData\Local\anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([443275.])

In [18]:
-153.45*3000+3*-106395.+40* 8565.+1209654.999999999

772719.9999999991

In [19]:
pip install word2number


  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5590 sha256=f6a525c64e7577a8633105131a5e54fd8a40d3798244911803e08c37074084ce
  Stored in directory: c:\users\lenovo\appdata\local\pip\cache\wheels\cd\ef\ae\073b491b14d25e2efafcffca9e16b2ee6d114ec5c643ba4f06
Successfully built word2number


In [ ]:
# https://docs.google.com/spreadsheets/d/17yKUw4eUkGLfldO_LwH0tDxpHJQHnuMLSZ43Geoc-l8/edit?usp=sharing

In [38]:
id1="17yKUw4eUkGLfldO_LwH0tDxpHJQHnuMLSZ43Geoc-l8"
xls1=pd.ExcelFile(f"https://docs.google.com/spreadsheets/d/{id1}/export?format=xlsx")
df1=pd.read_excel(xls1)
df1

experience  test_score  interview_score(out of 10)  salary
0       zero         8.0                           9   50000
1       zero         8.0                           6   45000
2       five         6.0                           7   60000
3        two        10.0                          10   65000
4      seven         9.0                           6   70000
5      three         7.0                          10   62000
6        ten         NaN                           7   72000
7     eleven         7.0                           8   80000

In [25]:
from word2number import w2n

In [39]:
df1['experience'] = df1['experience'].apply(w2n.word_to_num)

In [40]:
df1

experience  test_score  interview_score(out of 10)  salary
0           0         8.0                           9   50000
1           0         8.0                           6   45000
2           5         6.0                           7   60000
3           2        10.0                          10   65000
4           7         9.0                           6   70000
5           3         7.0                          10   62000
6          10         NaN                           7   72000
7          11         7.0                           8   80000

In [58]:
dd = df1.test_score.median()
dd

8.0

In [48]:
df1.test_score=df1.test_score.fillna(dd)

In [49]:
df1

experience  test_score  interview_score(out of 10)  salary
0           0         8.0                           9   50000
1           0         8.0                           6   45000
2           5         6.0                           7   60000
3           2        10.0                          10   65000
4           7         9.0                           6   70000
5           3         7.0                          10   62000
6          10         8.0                           7   72000
7          11         7.0                           8   80000

In [50]:
reg1=linear_model.LinearRegression()
reg1.fit(df1[['experience','test_score','interview_score(out of 10)']],df1.salary)

LinearRegression()

In [51]:
reg1.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [52]:
reg1.intercept_

17737.26346433771

In [54]:
reg1.predict([[2,9,6]])

D:\Users\Lenovo\AppData\Local\anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [55]:
#verify
2812.95487627*2+1845.70596798*9+2205.24017467*6+17737.26346433771

53205.967976717715

In [65]:
reg1.predict([[12,10,10]])

D:\Users\Lenovo\AppData\Local\anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])